import json
from datetime import datetime
from typing import Dict, Any

class ReportGenerator:
    def __init__(self, analysis_data: Dict[str, Any]):
        self.data = analysis_data

    def to_json(self) -> str:
        """Returns the analysis data as a JSON string."""
        # Use default=str to handle datetime objects if any
        return json.dumps(self.data, indent=2, default=str)

    def to_markdown(self) -> str:
        """Generates a Markdown report from the analysis data."""
        repo_url = self.data.get("repo_url", "Unknown Repo")
        scores = self.data.get("scores", {})
        signals = self.data.get("signals", {})
        findings = self.data.get("findings", [])
        
        md = []
        md.append(f"# Repository Analysis: {repo_url}")
        md.append(f"**Date:** {self.data.get('timestamp')}")
        md.append("")
        
        # Executive Summary / Scores
        md.append("## Executive Summary")
        md.append("| Metric | Score | Status |")
        md.append("| :--- | :--- | :--- |")
        md.append(f"| **Quality** | {scores.get('quality', 0)}/100 | {self._get_status(scores.get('quality', 0), True)} |")
        md.append(f"| **Cloud Readiness** | {scores.get('cloud_readiness', 0)}/100 | {self._get_status(scores.get('cloud_readiness', 0), True)} |")
        md.append(f"| **Risk** | {scores.get('risk', 0)}/100 | {self._get_status(scores.get('risk', 0), False)} |")
        md.append("")

        # Key Findings
        if findings:
            md.append("## Key Findings")
            for finding in findings:
                icon = "🔴" if finding['severity'] == "High" else "MF" if finding['severity'] == "Medium" else "🔵"
                md.append(f"### {icon} {finding['title']}")
                md.append(f"**Severity:** {finding['severity']}")
                md.append(f"{finding['description']}")
                if finding.get('evidence'):
                    md.append("**Evidence:**")
                    for ev in finding['evidence']:
                         md.append(f"- `{ev}`")
                md.append("")
        
        # Detailed Signals
        md.append("## Detailed Signals")
        
        md.append("### Hygiene & Standards")
        md.append(f"- **README:** {'✅ Found' if signals.get('has_readme') else '❌ Missing'}")
        md.append(f"- **Manifests:** {', '.join(signals.get('manifests_found', [])) or 'None'}")
        
        md.append("### CI/CD")
        md.append(f"- **CI System:** {'✅ ' + ', '.join(signals.get('ci_providers', [])) if signals.get('has_ci') else '❌ None detected'}")
        
        md.append("### Testing")
        md.append(f"- **Tests:** {'✅ Detected' if signals.get('has_tests') else '⚠️ Not detected'}")

        md.append("### Infrastructure & Cloud")
        md.append(f"- **Docker:** {'✅ Present' if signals.get('has_docker') else '⚪ Not found'}")
        if signals.get('dockerfile_issues'):
            md.append("  - **Issues:**")
            for issue in signals.get('dockerfile_issues'):
                md.append(f"    - ⚠️ {issue}")
        
        md.append(f"- **IaC:** {'✅ ' + ', '.join(signals.get('iac_providers', [])) if signals.get('has_iac') else '⚪ None'}")

        md.append("### Security & Risk")
        md.append(f"- **Secrets Smell:** {'🚨 Potential secrets found' if signals.get('has_secrets_smell') else '✅ Clean'}")
        if signals.get('potential_secrets_found'):
            for secret in signals.get('potential_secrets_found'):
                # Redact actual secret part if displayed (here we just show file location mostly)
                md.append(f"  - ⚠️ {secret}")

        md.append("")
        md.append("---")
        md.append("*Generated by repo-intel-bundle-v2*")

        return "\n".join(md)

    def _get_status(self, score: int, higher_is_better: bool) -> str:
        if higher_is_better:
            if score >= 80: return "🟢 Excellent"
            if score >= 50: return "🟡 Fair"
            return "🔴 Poor"
        else: # Lower is better (Risk)
            if score < 20: return "🟢 Low"
            if score < 50: return "🟡 Medium"
            return "🔴 High"
